--  This package was generated by the Ada_Drivers_Library project wizard script
package ADL_Config is
   Board                          : constant String  := "STM32L0538_Discovery"; -- From command line
   Architecture                   : constant String  := "ARM";               -- From board definition
   Vendor                         : constant String  := "STMicro";           -- From board definition
   Device_Family                  : constant String  := "STM32L0";           -- From board definition
   Device_Name                    : constant String  := "STM32L053x8x";      -- From board definition
   CPU_Core                       : constant String  := "ARM Cortex-M0";     -- From mcu definition
   Number_Of_Interrupts           : constant         := 0;                   -- From default value
   Has_ZFP_Runtime                : constant String  := "False";             -- From board definition
   Has_Ravenscar_SFP_Runtime      : constant String  := "True";              -- From board definition
   Has_Ravenscar_Full_Runtime     : constant String  := "True";              -- From board definition
   Runtime_Profile                : constant String  := "ravenscar-sfp";     -- From command line
   Runtime_Name_Suffix            : constant String  := "stm32l0538disco";   -- From board definition
   Runtime_Name                   : constant String  := "ravenscar-sfp-stm32l0538disco"; -- From default value
   Use_Startup_Gen                : constant Boolean := False;               -- From command line
   Max_Path_Length                : constant         := 1024;                -- From default value
   Max_Mount_Points               : constant         := 2;                   -- From default value
   Max_Mount_Name_Length          : constant         := 128;                 -- From default value
end ADL_Config;
